version: '3.0.{build}.0'

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  nuget restore YUICompressor.sln

build:
  parallel: true
  project: 'YUICompressor.sln'
  publish_nuget: true

after_build:
  - cmd: nuget pack Build\NuSpecs\YUICompressor.NET.nuspec -version "%APPVEYOR_BUILD_VERSION%"

artifacts:
  path: '**\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: srBMVDnPbP0bAvQALTu0Pi+wQWUWCSDExxmbN5HQ/kDXQvvzf/hPwdV5e4zBnhVG
  artifact: /YUICompressor.*\.nupkg/
  skip_symbols: false
